### ISSUE TITLE
Umbrella 1.0

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#164]
- [x] Decide on API changes needed for time travel and similar tools (#113)
- [x] Remove the dispatcher (<s>#166</s> #195)
- [x] Pass `dispatch` to middleware (<s>#120</s> #195)
- [x] Make sure nested dispatches are fixed (needs a test from #119, should be solved by #195)
- [x] Finalize terminology (#140, #195)
- [x] Throw in `composeReducers` if either returns `undefined` (#191, #193)
- [x] Decide on API for binding action creators (#86)
- [x] Release DevTools (#113)
- [x] Fix build on Windows (#94)
- [x] Split packages (https://github.com/gaearon/redux/issues/230)
- [x] Merge https://github.com/gaearon/redux/pull/295
- [x] Merge https://github.com/gaearon/redux/pull/302
- [x] Create new docs (#140)

**Comment by gaearon** [comment]
While most of these already have PRs ready to be merged, I would like to finish my work in #113 (I have a proof of concept and now need to take some time to figure out the right API). This is to avoid two API changes in a row. Thanks everyone for your hard work and please be patient for a few more days. ;-)

**Comment by gaearon** [comment]
1.0 is out.
