### ISSUE TITLE
Umbrella 2.0

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#670]
- [x] **(Breaking)** Remove `getReducer()` from the Store public API (#668)
- [x] **(Breaking)** Fix `compose()` to act like a normal `compose()` (https://github.com/rackt/redux/issues/669) 
- [x] **(Breaking)** Rely on `process.env.NODE_ENV` being polyfilled (https://github.com/rackt/redux/pull/671)
- [x] Release Redux 2.0
- [x] Update React Redux to stop using `getReducer()` and release 2.0
- [x] Update Redux DevTools to use Redux 2.0 and React Redux 2.0, update its examples, and release 2.0
